server:
  port: 8100

spring:

  application:
    name: cmsplus-batch

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


exchange:
  authKey: EXCHANGE_AUTHKEY
  data: EXCHANGE_DATA

logging:
  level:
    sql: debug