server:
  port: 8100

spring:
  profiles:
    active: dev
  application:
    name: cmsplus-batch
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

kafkaServer:
  ip: ${KAFKASERVER_IP}

kafkaTopic:
  messagingTopic: ${MESSAGING_TOPIC}

#logging:
#  level:
#    sql: debug