version: '3.8'

networks:
  elk:
    driver: bridge

services:

  db:
    container_name: mysql
    build:
      # context: ./database
      context: ./server-batch
      dockerfile: Dockerfile
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
