server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: cmsplus-main
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    sql: debug
#    org.hibernate.orm.jdbc.bind: trace

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

kafkaTopic:
  messagingTopic: ${MESSAGING_TOPIC}
  paymentTopic: ${PAYMENT_TOPIC}
  paymentResultTopic: ${PAYMENT_RESULT_TOPIC}
  monitoringTopic: ${MONITORING_TOPIC}