spring:
  application:
    name: cmsplus-main

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmsplusmain?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1004

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

cloud:
  aws:
    s3:
      bucket: <버킷이름>
    stack.auto: false
    region.static:
    credentials:
      accessKey: <발급받은 accessKey>
      secretKey: <발급받은 secretKey>