spring:
  application:
    name: cmsplus-main
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdba
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmsplusmain?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1004

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

coolsms:
  api-key: NCS6FSXZJNQ2W4VB
  api-secret: PW7L7IUM5REUVNL0HYKANDIL7XSLBRHK
  sender-number: 01026270378