server:
  port: 8090

spring:
  application:
    name: cmsplusmessage
  kafka:
    consumer:
#      group-id: sms-group
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
      # auto-offset-reset
      # latest(default): ?? ??? offset??
      # earliest: ?? ?? offset??(consumer???? ?? ??? / producer???? ?? ?? ??)
      # none: ????? topic? offset? ??? ?? ??



coolsms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
    domain: ${SMS_DOMAIN}
    phone: ${SMS_PHONE}