name: Analysis CICD

on:
  push:
    branches:
      - dev
    paths:
      - 'server-analysis/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/server-analysis:latest ./server-analysis
        docker push ${{ secrets.DOCKER_USERNAME }}/server-analysis:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BATCH_EC2_HOST }}
        username: ${{ secrets.BATCH_EC2_USER }}
        key: ${{ secrets.T3_KEYPAIR_PEM }}
        port: 22
        script: |
          sudo docker image pull ${{ secrets.DOCKER_USERNAME }}/server-analysis:latest
          
          # Stop and remove the existing container if it is running
          if [ $(sudo docker ps -q -f name=server-analysis) ]; then
            sudo docker stop server-analysis
            sudo docker rm server-analysis
          fi

          # Run the new container
          sudo docker run -d -p 80:8888 --name server-analysis ${{ secrets.DOCKER_USERNAME }}/server-analysis:latest
