name: Kafka CICD

on:
  push:
    branches:
      - dev
    paths:
      - 'server-kafka/**'

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: t3-back-kafka
  COMPOSE_FILE: server-kafka/docker-compose.yml
  ECS_CLUSTER: t3-back-ecscluster
  ECS_SERVICE_NAME: t3-back-kafkaservice
  AWS_DEFAULT_REGION: ap-northeast-2

permissions:
  contents: read

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Images
      run: |
        docker compose -f ${{ env.COMPOSE_FILE }} build
        docker compose -f ${{ env.COMPOSE_FILE }} push

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ env.AWS_REGION }}
        aws ecs describe-clusters --clusters ${{ env.ECS_CLUSTER }} --region ${{ env.AWS_REGION }}

    - name: Create and Use ECS context
      run: |
        docker context create ecs myecscontext --description "ECS context for Kafka"
        docker context use myecscontext

    - name: Deploy to ECS
      run: |
        docker compose -f ${{ env.COMPOSE_FILE }} up
