name: MESSAGING CICD

on:
  push:
    branches:
      - dev
    paths:
      - 'server-messaging/**'

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: t3-back-messagingecr
  ECS_CLUSTER: t3-back-ecscluster
  ECS_CONTAINER: t3-back-messagingcontainer
  ECS_SERVICE: t3-back-messagingservice

  ECS_TASK_DEFINITION: task-definition-messaging.json


permissions:
  contents: read

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x server-messaging/gradlew

    - name: Add secure properties
      run: echo "${{ secrets.MESSAGING_SECURE_DEV }}" > server-messaging/src/main/resources/secure.properties

    - name: Build with Gradle
      run: |
        cd server-messaging
        ./gradlew clean build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1 

    - name: Build, tag, and push Docker image
      env:
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        docker build -t $ECR_REPOSITORY:latest server-messaging/dockerfile .
        docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

    - name: Register ECS Task Definition
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        aws ecs register-task-definition --cli-input-json file://${{ env.ECS_TASK_DEFINITION }}

    - name: Deploy to ECS Service
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment