# name: PAYMENT CICD

# on:
#   push:
#     branches:
#       - dev
#     paths:
#       - 'server-payment/**'

# env:
#   AWS_REGION: ap-northeast-2
#   ECR_REPOSITORY: t3-back-mainecr
#   ECS_CLUSTER: t3-back-ecscluster
#   ECS_CONTAINER: t3-back-maincontainer
#   ECS_SERVICE: t3-back-mainservice

#   ECS_TASK_DEFINITION: task-definition.json


# permissions:
#   contents: read

# jobs:
#   ci-cd:
#     runs-on: ubuntu-latest
#     environment: production

